INSERT INTO DEPT_TB(DNAME, LOC) VALUES ('財務部','臺灣台北');
INSERT INTO DEPT_TB(DNAME, LOC) VALUES ('研發部','臺灣新竹');
INSERT INTO DEPT_TB(DNAME, LOC) VALUES ('業務部','美國紐約');
INSERT INTO DEPT_TB(DNAME, LOC) VALUES ('生管部','中國上海');