INSERT INTO COUNTRY (ID, NAME) VALUES (1, 'USA');
INSERT INTO COUNTRY (ID, NAME) VALUES (2, 'France');
INSERT INTO COUNTRY (ID, NAME) VALUES (3, 'Brazil');
INSERT INTO COUNTRY (ID, NAME) VALUES (4, 'Italy');
INSERT INTO COUNTRY (ID, NAME) VALUES (5, 'Canada');