CREATE TABLE COUNTRY
(
    ID           INTEGER      NOT NULL AUTO_INCREMENT,
    NAME         VARCHAR(128) NOT NULL,
    MEMORIAL_DAY DATE         NOT NULL DEFAULT '2022-01-01',
    PRIMARY KEY (ID)
);